
language: node_js

node_js:
  - "node"

script: npm test

before_script:
    - npm install
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"

after_script: cat ./coverage/**/lcov.info | ./node_modules/.bin/coveralls
